# Generated by Django 6.0.7 on 2026-08-31 03:38

import contas.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text='Identificador estável usado no código (ex.: previsao_chuva_24_48h).', max_length=60, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Funcionalidade',
                'verbose_name_plural': 'Funcionalidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('gestor', 'Gestor'), ('usuario', 'Usuário')], default='usuario', max_length=10)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', contas.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(help_text='Ex.: "estacao.criada", "usuario.suspenso", "plano.alterado".', max_length=100)),
                ('alvo_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alvo_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('ator', models.ForeignKey(help_text='Quem executou a ação. SET_NULL (não CASCADE): o log sobrevive mesmo se a conta do ator for removida.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de auditoria',
                'verbose_name_plural': 'Logs de auditoria',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Usado só para ordenar a exibição (0=Standard, 1=Pro, 2=Plus...).')),
                ('max_estacoes', models.PositiveIntegerField(blank=True, help_text='Limite de estações vinculadas (RN10). Vazio = ilimitado (ex.: Plus).', null=True)),
                ('dias_historico', models.PositiveIntegerField(help_text='Quantos dias de histórico o Usuário enxerga no dashboard (RN29). A retenção física no banco pode ser maior — isso aqui é só o que é exibido.')),
                ('canais_alerta', models.JSONField(blank=True, default=list, help_text='Canais de notificação liberados neste plano (RN13), ex.: ["email", "dashboard", "telefone"].')),
                ('preco_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('funcionalidades', models.ManyToManyField(blank=True, help_text='Recursos/modelos analíticos liberados por este plano (RN09, RN24).', related_name='planos', to='contas.funcionalidade')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inadimplente', 'Inadimplente'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='ativa', max_length=15)),
                ('origem', models.CharField(choices=[('autoatendimento', 'Autoatendimento'), ('gestor', 'Alteração manual do Gestor')], default='autoatendimento', max_length=20)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('encerrada_em', models.DateTimeField(blank=True, help_text='Preenchido quando o usuário troca de plano ou cancela.', null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='contas.plano')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-iniciada_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('encerrada_em__isnull', True)), fields=('usuario',), name='uma_assinatura_ativa_por_usuario')],
            },
        ),
    ]
