# Generated by Django 6.0.7 on 2026-08-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_seed_planos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenCredenciamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField(unique=True)),
                ('token_hash', models.CharField(max_length=128)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token de credenciamento',
                'verbose_name_plural': 'Tokens de credenciamento',
                'ordering': ['-versao'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='usuario',
            name='credenciamento_versao',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
