# Generated by Django 6.0.7 on 2026-08-31 06:10
#
# `cpf` passa a ter unique=True — mas contas antigas (criadas antes desse
# campo existir de verdade, ex. via createsuperuser/admin) ficaram com
# cpf='' (string vazia), não NULL. Duas strings vazias violariam a
# constraint de unicidade — e o banco não deixa fazer UPDATE pra NULL
# antes da coluna aceitar NULL. Por isso em 3 passos: 1) permite NULL
# (sem unique ainda), 2) converte '' -> NULL, 3) acrescenta unique=True.

from django.db import migrations, models


def limpar_cpfs_vazios(apps, schema_editor):
    Usuario = apps.get_model('contas', 'Usuario')
    Usuario.objects.filter(cpf='').update(cpf=None)


def reverter_cpfs_vazios(apps, schema_editor):
    Usuario = apps.get_model('contas', 'Usuario')
    Usuario.objects.filter(cpf__isnull=True).update(cpf='')


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_definir_precos_planos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, help_text='Só dígitos, sem pontuação.', max_length=11, null=True),
        ),
        migrations.RunPython(limpar_cpfs_vazios, reverter_cpfs_vazios),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, help_text='Só dígitos, sem pontuação.', max_length=11, null=True, unique=True),
        ),
    ]
