# Generated by Django 6.0.7 on 2026-08-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contas', '0006_usuario_email_verificado_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, help_text='Só dígitos, sem pontuação.', max_length=11, null=True),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('cpf', 'role'), name='cpf_unico_por_papel'),
        ),
    ]
