# Generated by Django 6.0.7 on 2026-09-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contas', '0007_alter_usuario_options_alter_usuario_cpf_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email', 'role'), name='email_unico_por_papel'),
        ),
    ]
