# Generated by Django 6.0.7 on 2026-09-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_usuario_email_unico_por_papel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.CharField(blank=True, help_text='Formato: 00000-000.', max_length=9),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, help_text='Sigla UF, ex.: RJ.', max_length=2),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rua',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
