# Generated by Django 6.0.7 on 2026-10-08 20:19

import contas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0009_usuario_cep_usuario_cidade_usuario_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='variaveis_padrao',
            field=models.JSONField(default=contas.models._todas_variaveis_padrao, help_text='Variáveis que uma conta deste plano enxerga por padrão em cada estação vinculada (temperatura/umidade/pressao/vento/chuva/radiacao) — sugestão inicial ao vincular (RF-03); o Gestor pode restringir manualmente por conta+estação depois (ver AcessoEstacao em api_rest/models.py), que é quem de fato vale.'),
        ),
    ]
