"""
Django settings for api_root project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Lê as variáveis do arquivo .env (veja .env.example) e as coloca em os.environ.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-6#r*489t)%j4$o81rf-eg)o*4$52xk+b_*sre=vi%phoy+2zg-',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Em produção (Render), defina ALLOWED_HOSTS com o domínio da aplicação,
# por exemplo: ALLOWED_HOSTS=meu-projeto.onrender.com
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'contas',
    'api_rest',
]

# Usuario customizado (app contas) no lugar do auth.User padrão do Django —
# Gestor e Usuário final são o mesmo model, diferenciados por um campo
# `role` (ver contas/models.py). Precisa estar definido ANTES da primeira
# migration que referencia usuário ser aplicada.
AUTH_USER_MODEL = 'contas.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api_root.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api_root.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Um único banco PostgreSQL para tudo: tabelas internas do Django
# (autenticação, sessões) e as leituras meteorológicas (app api_rest).
# Em produção, DATABASE_URL aponta para o projeto no Supabase; localmente
# tem como padrão o Postgres de desenvolvimento (veja o README).

# dj_database_url.config() faz o próprio lookup de DATABASE_URL no ambiente,
# e ignora o "default" se a variável existir só que vazia (caso do .env
# antes de ser preenchida) — por isso resolvemos a string nós mesmos e
# usamos parse() em vez de config().
_database_url = os.environ.get('DATABASE_URL') or 'postgresql://teste:teste@localhost:5433/monitoramento_meteorologico'

# conn_max_age=0 (padrão): fecha a conexão a cada request em vez de
# mantê-la aberta. Necessário enquanto DATABASE_URL apontar para o
# "Session pooler" do Supabase (free tier, limite de 15 conexões
# simultâneas) — conexões persistentes prendiam uma vaga por minutos e
# esgotavam esse limite rapidinho.
#
# Efeito colateral medido em produção: abrir uma conexão nova a cada
# request custa ~1-1.5s (handshake com o Postgres do Supabase), e
# /api/rssi/status/ é chamado pelo ESP32 de forma síncrona/bloqueante a
# cada leitura — esse custo trava a recepção LoRa.
#
# Correção: trocar a connection string do Supabase pro "Transaction
# pooler" (porta 6543, pgbouncer) — ele multiplexa muitas conexões da
# aplicação sobre poucas conexões reais, então dá pra manter a conexão
# viva sem esgotar o limite. Depois de trocar o DATABASE_URL no Render,
# defina DB_CONN_MAX_AGE=60 (variável de ambiente, não vai pro código) —
# só então esse valor passa a ser usado; sem a variável, continua 0
# (comportamento atual, seguro com o Session pooler).
_conn_max_age = int(os.environ.get('DB_CONN_MAX_AGE', '0'))

DATABASES = {
    'default': dj_database_url.parse(_database_url, conn_max_age=_conn_max_age)
}


# Django REST Framework
# Autenticação via JWT (access + refresh token) para Gestor/Usuário (RN20).
# As views que o hardware (ESP32) chama diretamente continuam com
# permission_classes = [AllowAny] explícito nelas mesmas — a estação ainda
# não manda token nenhum (isso fica para quando o firmware for adaptado),
# então o padrão do projeto (IsAuthenticated) não pode se aplicar a elas.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# CORS
# Como esta API ainda não tem autenticação, liberamos todas as origens
# para simplificar. Se um dia houver um frontend específico, troque por
# CORS_ALLOWED_ORIGINS = ['https://meu-frontend.com'].
CORS_ALLOW_ALL_ORIGINS = True


# E-mail (confirmação de cadastro — contas/emails.py)
#
# Provedor configurado via variável de ambiente RESEND_API_KEY (SMTP do
# Resend: https://resend.com, tem plano gratuito). Enquanto essa variável
# não existir (ex.: ambiente local sem configurar nada), o Django usa o
# backend de console — o e-mail "é enviado" só no sentido de aparecer
# impresso no log do servidor, ninguém recebe de verdade. Isso deixa o
# fluxo inteiro testável sem depender de provedor nenhum, e vira envio
# real assim que a variável for definida — sem mudar código.
_resend_api_key = os.environ.get('RESEND_API_KEY')

if _resend_api_key:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.resend.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'resend'
    EMAIL_HOST_PASSWORD = _resend_api_key
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'onboarding@resend.dev')

# URL do frontend publicado — usada para montar o link de confirmação de
# e-mail (contas/emails.py). Em produção, defina FRONTEND_URL com o
# domínio real do Vercel; em dev local aponta pro Vite.
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

