# Generated by Django 6.0.7 on 2026-07-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=100)),
                ('temperatura', models.FloatField()),
                ('umidade', models.FloatField()),
                ('pressao', models.FloatField(blank=True, null=True)),
                ('dados_adicionais', models.JSONField(blank=True, default=dict)),
                ('data_hora', models.DateTimeField()),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
