# Generated by Django 6.0.7 on 2026-08-31 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_solicitacaorssi_por_sensor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leitura',
            name='inconsistente',
            field=models.BooleanField(default=False, help_text='RN18: valor fora de faixa fisicamente plausível (ex.: umidade > 100%). A leitura é armazenada mesmo assim (para auditoria), só fica marcada para ser excluída dos modelos preditivos.'),
        ),
        migrations.AddField(
            model_name='leitura',
            name='motivo_inconsistencia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='leitura',
            name='sensor_id',
            field=models.CharField(help_text='Identificador cru enviado pelo dispositivo (campo "sensor" do payload). Mantido tal como está por compatibilidade com o firmware atual.', max_length=100),
        ),
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Mesmo valor que o firmware envia como "sensor" (ex.: ESP32_01). É o que liga uma Leitura recebida a esta Estação.', max_length=100, unique=True)),
                ('nome', models.CharField(blank=True, help_text='Nome amigável, exibido no dashboard.', max_length=150)),
                ('token_hash', models.CharField(blank=True, help_text='Hash do token de autenticação do dispositivo (RN14). Vazio = token ainda não emitido.', max_length=128)),
                ('intervalo_envio_minutos', models.PositiveSmallIntegerField(choices=[(5, '5 minutos'), (10, '10 minutos'), (15, '15 minutos')], default=10, help_text='Intervalo esperado entre transmissões (RN16), usado para calcular se está offline.')),
                ('limite_offline_minutos', models.PositiveSmallIntegerField(default=30, help_text='Minutos sem transmitir até considerar a estação "offline" (RN17).')),
                ('ultima_transmissao_em', models.DateTimeField(blank=True, help_text='Atualizado a cada leitura recebida com sucesso (RN16).', null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('dono', models.ForeignKey(help_text='Usuário (ou Gestor) responsável pela estação (RN15: toda estação tem exatamente um dono, nunca fica "órfã"). PROTECT: não deixa apagar um usuário que ainda tem estação vinculada.', on_delete=django.db.models.deletion.PROTECT, related_name='estacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estação',
                'verbose_name_plural': 'Estações',
                'ordering': ['identificador'],
            },
        ),
        migrations.AddField(
            model_name='leitura',
            name='estacao',
            field=models.ForeignKey(blank=True, help_text='Resolvida automaticamente a partir de sensor_id no momento do POST, quando a Estacao correspondente já estiver cadastrada. Nula = estação ainda não cadastrada (a leitura é salva mesmo assim, sem dono, como sempre foi).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leituras', to='api_rest.estacao'),
        ),
        migrations.AddField(
            model_name='solicitacaorssi',
            name='estacao',
            field=models.ForeignKey(blank=True, help_text='Preenchido por resolução automática a partir de sensor_id, quando a Estacao já existir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_rssi', to='api_rest.estacao'),
        ),
        migrations.AddIndex(
            model_name='leitura',
            index=models.Index(fields=['estacao', '-data_hora'], name='api_rest_le_estacao_0f2240_idx'),
        ),
    ]
