# Generated by Django 6.0.7 on 2026-09-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_leitura_inconsistente_leitura_motivo_inconsistencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='localizacao',
            field=models.CharField(blank=True, help_text='Local em texto livre (ex.: "Área de Plantio - Talhão 2"), preenchido pelo Gestor — não vem do dispositivo.', max_length=200),
        ),
    ]
