# Generated by Django 6.0.7 on 2026-09-08 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_estacao_localizacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='usuarios',
            field=models.ManyToManyField(blank=True, help_text='Contas com acesso a esta estação (RN15). Não existe "dono" único — o Gestor pode vincular quantas contas quiser à mesma estação física; todas enxergam os mesmos dados, sem hierarquia entre elas. Só o Gestor administra o vínculo (adicionar/remover conta, editar, excluir).', related_name='estacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='dono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='_estacoes_dono_migracao_temp', to=settings.AUTH_USER_MODEL),
        ),
    ]
