# Generated by Django 6.0.7 on 2026-09-08 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0007_migrar_dono_para_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacao',
            name='dono',
        ),
    ]
