# Generated by Django 6.0.7 on 2026-10-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0008_remove_estacao_dono'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSincronizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuvem_alcancavel', models.BooleanField(default=False)),
                ('ultima_tentativa_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_sincronizacao_com_sucesso_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
