# Generated by Django 6.0.7 on 2026-10-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0009_estadosincronizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Só preenchido para tipo=online — coordenada usada para consultar a Open-Meteo.', null=True),
        ),
        migrations.AddField(
            model_name='estacao',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Só preenchido para tipo=online — coordenada usada para consultar a Open-Meteo.', null=True),
        ),
        migrations.AddField(
            model_name='estacao',
            name='tipo',
            field=models.CharField(choices=[('fisica', 'Física'), ('online', 'Online')], default='fisica', help_text='Define de onde vêm os dados: "fisica" é hardware real (ESP32/LoRa) enviando via POST /api/leituras/; "online" é uma estação virtual, sem hardware, cujas leituras são coletadas periodicamente da Open-Meteo pelo comando coletar_dados_online (ver api_rest/management/commands/). NÃO confundir com `esta_offline` abaixo — aquela propriedade é sobre CONECTIVIDADE (RN17, se parou de transmitir recentemente) e existe igualmente para os dois tipos; esta aqui é sobre a FONTE do dado.', max_length=10),
        ),
    ]
