# Generated by Django 6.0.7 on 2026-10-08 20:19 — editada à mão: Django
# não permite trocar o through= de um M2M via AlterField direto ("you
# cannot alter to or from M2M fields, or add or remove through= on M2M
# fields"). Sequência correta: cria a tabela nova (vazia) -> copia os
# vínculos já existentes da tabela M2M implícita antiga pra ela -> só
# ENTÃO remove o campo antigo (que apaga a tabela implícita) e recria o
# campo apontando pro through novo. Sem o passo do meio, todo vínculo
# usuário-estação já cadastrado seria perdido silenciosamente.
import api_rest.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copiar_vinculos_existentes(apps, schema_editor):
    alias = schema_editor.connection.alias
    Estacao = apps.get_model('api_rest', 'Estacao')
    AcessoEstacao = apps.get_model('api_rest', 'AcessoEstacao')
    for estacao in Estacao.objects.using(alias).all():
        for usuario in estacao.usuarios.using(alias).all():
            AcessoEstacao.objects.using(alias).get_or_create(estacao=estacao, usuario=usuario)


def copiar_vinculos_de_volta(apps, schema_editor):
    """Reverso: só pra permitir `migrate` andar pra trás em dev."""
    alias = schema_editor.connection.alias
    Estacao = apps.get_model('api_rest', 'Estacao')
    AcessoEstacao = apps.get_model('api_rest', 'AcessoEstacao')
    for acesso in AcessoEstacao.objects.using(alias).all():
        Estacao.objects.using(alias).get(pk=acesso.estacao_id).usuarios.add(acesso.usuario_id)


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0010_estacao_latitude_estacao_longitude_estacao_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoEstacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variaveis_liberadas', models.JSONField(default=api_rest.models.todas_variaveis, help_text='Subconjunto de AcessoEstacao.VARIAVEIS que esta conta pode ver nesta estação.')),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.estacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso à estação',
                'verbose_name_plural': 'Acessos às estações',
            },
        ),
        migrations.RunPython(copiar_vinculos_existentes, copiar_vinculos_de_volta),
        migrations.RemoveField(
            model_name='estacao',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='estacao',
            name='usuarios',
            field=models.ManyToManyField(blank=True, help_text='Contas com acesso a esta estação (RN15). Não existe "dono" único — o Gestor pode vincular quantas contas quiser à mesma estação física; todas enxergam os mesmos dados, sem hierarquia entre elas. Só o Gestor administra o vínculo (adicionar/remover conta, editar, excluir). Quais VARIÁVEIS cada uma vê fica no through model AcessoEstacao, não aqui.', related_name='estacoes', through='api_rest.AcessoEstacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='acessoestacao',
            constraint=models.UniqueConstraint(fields=('usuario', 'estacao'), name='acesso_unico_por_conta_estacao'),
        ),
    ]
