# Generated by Django 6.0.7 on 2026-10-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0011_acessoestacao_alter_estacao_usuarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacao',
            name='intervalo_envio_minutos',
            field=models.PositiveSmallIntegerField(choices=[(5, '5 minutos'), (10, '10 minutos'), (15, '15 minutos'), (60, '1 hora')], default=10, help_text='Intervalo esperado entre transmissões (RN16), usado para calcular se está offline.'),
        ),
    ]
